server:
  port: 8090

spring:
    application:
        name: student
    datasource:
        url: jdbc:mysql://localhost:3306/student?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.MySQL8Dialect
        database: mysql
    config:
        import: optional:configserver:http://localhost:8888

eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
